# iRonCub-Mk3 config file

[Model]
Base_link = "root_link"

[Joints]
List = [
    "torso_pitch",
    "torso_roll",
    "torso_yaw",
    "l_shoulder_pitch",
    "l_shoulder_roll",
    "l_shoulder_yaw",
    "l_elbow",
    "r_shoulder_pitch",
    "r_shoulder_roll",
    "r_shoulder_yaw",
    "r_elbow",
    "l_hip_pitch",
    "l_hip_roll",
    "l_hip_yaw",
    "l_knee",
    "l_ankle_pitch",
    "l_ankle_roll",
    "r_hip_pitch",
    "r_hip_roll",
    "r_hip_yaw",
    "r_knee",
    "r_ankle_pitch",
    "r_ankle_roll",
]
Frames = [
    "head",
    "chest_l_jet_turbine",
    "chest_r_jet_turbine",
    "l_upper_arm",
    "l_shoulder_1",
    "l_shoulder_2",
    "l_arm_jet_turbine",
    "l_lower_leg",
    "l_hip_1",
    "l_upper_leg",
    "l_hip_3",
    "r_upper_arm",
    "r_shoulder_1",
    "r_shoulder_2",
    "r_arm_jet_turbine",
    "r_lower_leg",
    "r_hip_1",
    "r_upper_leg",
    "r_hip_3",
    "root_link",
    "chest",
    "torso_1",
    "torso_2",
]
Limits = [
    [-20.0, 70.0], [-30.0, 30.0], [-50.0, 50.0], # torso joints
    [-90.0, 10.0], [0.0, 160.0], [-35.0, 80.0], [17.0, 105.0], # left arm joints
    [-90.0, 10.0], [0.0, 160.0], [-35.0, 80.0], [17.0, 105.0], # right arm joints
    [-35.0, 80.0], [-15.0, 90.0], [-70.0, 70.0], [-100.0, 0.0], # left leg joints [no ankles:[-45.0, 45.0], [-25.0, 25.0]]
    [-35.0, 80.0], [-15.0, 90.0], [-70.0, 70.0], [-100.0, 0.0], # right leg joints [no ankles:[-45.0, 45.0], [-25.0, 25.0]]
]

[Collisions]
FramesList = [
    # "l_arm_jet_turbine",
    # "r_arm_jet_turbine",
    "l_arm_jet_turbine",
    "r_arm_jet_turbine",
    # "chest_l_jet_turbine",
    # "chest_r_jet_turbine",
    "chest_l_jet_turbine",
    "chest_r_jet_turbine",
    # "l_upper_arm",
    # "r_upper_arm",
    "l_upper_leg",
    "r_upper_leg",
    "l_lower_leg",
    "r_lower_leg",
    "l_foot",
    "r_foot",
    # "root_link",
    # "chest",
]
Centers = [
    # [0.0, 0.0, -0.05], [0.0, 0.0, -0.1], [0.0, 0.0, -0.15], [0.0, 0.0, -0.2], # left arm turbine
    # [0.0, 0.0, -0.05], [0.0, 0.0, -0.1], [0.0, 0.0, -0.15], [0.0, 0.0, -0.2], # right arm turbine
    [0.0, 0.0, 0.0], [0.0, 0.0, 0.0279], [0.0, 0.0, 0.056], [0.0, 0.0, 0.112], [0.0, 0.0, 0.15], [0.0, 0.0, 0.186], [0.0, 0.0, 0.25], [0.0, 0.0, 0.3], [0.0, 0.0, 0.35], [0.0, 0.0, 0.4],# left arm turbine jet cone
    [0.0, 0.0, 0.0], [0.0, 0.0, 0.0279], [0.0, 0.0, 0.056], [0.0, 0.0, 0.112], [0.0, 0.0, 0.15], [0.0, 0.0, 0.186], [0.0, 0.0, 0.25], [0.0, 0.0, 0.3], [0.0, 0.0, 0.35], [0.0, 0.0, 0.4],# right arm turbine jet cone
    # [0.0, 0.0, -0.06], [0.0, 0.0, -0.12], [0.0, 0.0, -0.16], [0.0, 0.0, -0.225], # left jetpack turbine
    # [0.0, 0.0, -0.06], [0.0, 0.0, -0.12], [0.0, 0.0, -0.16], [0.0, 0.0, -0.225], # right jetpack turbine
    [0.0, 0.0, 0.0], [0.0, 0.0, 0.0342], [0.0, 0.0, 0.0687], [0.0, 0.0, 0.1374], [0.0, 0.0, 0.228], [0.0, 0.0, 0.3], [0.0, 0.0, 0.35], [0.0, 0.0, 0.4], [0.0, 0.0, 0.45], [0.0, 0.0, 0.5], [0.0, 0.0, 0.55], # left jetpack jet cone
    [0.0, 0.0, 0.0], [0.0, 0.0, 0.0342], [0.0, 0.0, 0.0687], [0.0, 0.0, 0.1374], [0.0, 0.0, 0.228], [0.0, 0.0, 0.3], [0.0, 0.0, 0.35], [0.0, 0.0, 0.4], [0.0, 0.0, 0.45], [0.0, 0.0, 0.5], [0.0, 0.0, 0.55], # right jetpack jet cone
    # [-0.015, 0.0, 0.005], [-0.015, 0.0, 0.05], # left upper arm
    # [-0.015, 0.0, 0.005], [-0.015, 0.0, 0.05], # right upper arm
    [0.005, 0.0, 0.01], [0.01, 0.0, -0.06], # left upper leg
    [0.005, 0.0, 0.01], [0.01, 0.0, -0.06], # right upper leg
    [0.01, 0.0, -0.04], [0.0, 0.0, -0.1], [0.0, 0.0, -0.14], # left lower leg
    [0.01, 0.0, -0.04], [0.0, 0.0, -0.1], [0.0, 0.0, -0.14], # right lower leg
    # [0.02, 0.05, -0.02], [0.02, -0.05, -0.02], [0.02, 0.0, -0.09], # base link
    # [0.0, 0.04, 0.01], [-0.045, 0.02, -0.1], [0.045, 0.02, -0.1], [0.0, 0.1, -0.1], # chest
    [-0.03, -0.005, -0.01], [0.02, -0.005, -0.01], [0.07, -0.005, -0.01], # left foot
    [-0.03, 0.005, -0.01], [0.02, 0.005, -0.01], [0.07, 0.005, -0.01],# right foot
]
Radii = [
    # [0.05, 0.055, 0.055, 0.055], [0.05, 0.055, 0.055, 0.055], # arm turbines
    [0.0245, 0.0294, 0.0314, 0.038, 0.043, 0.049, 0.059, 0.069, 0.079, 0.089], # left arm jet cone
    [0.0245, 0.0294, 0.0314, 0.038, 0.043, 0.049, 0.059, 0.069, 0.079, 0.089], # right arm jet cone
    # [0.05, 0.06, 0.06, 0.06], [0.05, 0.06, 0.06, 0.06], # jetpack turbines
    [0.03, 0.036, 0.0384, 0.0465, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12], # left jetpack jet cone
    [0.03, 0.036, 0.0384, 0.0465, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12], # right jetpack jet cone
    # [0.0475, 0.0475], [0.0475, 0.0475], # upper arms
    [0.06, 0.06], [0.06, 0.06], # upper legs
    [0.06, 0.06, 0.06], [0.06, 0.06, 0.06], # lower legs
    # [0.06, 0.06, 0.065], # base link
    # [0.08, 0.06, 0.06, 0.095], # chest
    [0.035, 0.035, 0.035], [0.035, 0.035, 0.035], # feet
]
